### ISSUE TITLE
Make /api/history

### ISSUE THREAD

**Issue by jkcclemens** [RoyalDev/TheHumanity#39]
```
/api/history/{channel} – Lists overview of previous games in channel
/api/history/{channel}/{game} – Game being a numeric ID obtained in the above route, lists summary of this game
/api/history/{channel}/{game}/{round} – Round being a numeric ID (round number) obtained in the above route, lists a summary of this round
```

**Comment by jkcclemens** [comment]
@turt2live and @kashike may have input on what they would like to see for their statistic recording and such.

**Comment by jkcclemens** [comment]
Might consider serializing this as JSON. Implementing Serializable will just be a huge pain in the ass. I can store all of the important information as JSON, since it's all a snapshot. Users don't need to retain modes, etc. Names are really all that matter. It's all strings. Mostly.

**Comment by turt2live** [comment]
Ideally for CAH_BOTZIE's workflow (described below) a lot of information would be best (also listed below).

Psuedo-JSON is used as a data format in the examples below. Names/format/organization/methods could be changed if needed.

Example workflow:
```
<TheHumanity> Round 2!
[ CAH_BOTZIE sees message and records data for round 1 ]
```

The information that would be helpful for CAH_BOTZIE in particular:
- Who participated in the round
- Who the czar was
  - If no czar, then some clear indication that a house rule intervened
  - If it's the voting house rule (idk name), then a list of votes placed. Example: `votes: [ {"turt2live": 1, "jkcclemens": 3} ]`
- Which cards the players picked
  - Ideally with currently non-visible data, if possible. Example: `picks: { "turt2live": [{cardIndex: 2, cardText: "..."}]}`
  - If player picks are not desired to be exposed, then at least the pick index(es) the players made would be best. Example: `picks: {"turt2live": [2, 4]}`
- Which hand won (index is fine)
- The hands played
- The black card
- Who won the round (player name)
- Points received during the round (would look stupid for now, but if >1 point is collected for winning in the future then this may help with score tracking)
  - At the very least a tallied score for "up-to-round" would be good enough
- How the round turned out
  - Was it skipped via !skip? Did the czar leave? etc...

This is what I imagine a small round looking like (JSON-ish format):
```
{
  number: 2
  players: [
    "turt2live"
    "jkcclemens"
  ]
  black-card: "You can always <BLANK> when you're <BLANK>."
  czar: null
  votes: {
    turt2live: 1
    jkcclemens: 3
  }
  cards-played: {
    turt2live: {
      czar-index: 1
      hand: [
        {
          hand-index: 2
          text: "..."
        },
        {
          hand-index: 3
          text: "..."
        }
      ]
    }
    jkcclemens: {...}
  }
  winner: "jkcclemens"
  scores: {
    turt2live: 0
    jkcclemens: 1
  }
  round-result: {
    skipped: false
    czar-left: false
    czar-picked: false
    voted-winner: true
  }
}
```

**Comment by turt2live** [comment]
CAH_BOTZIE also would track games (or "matches" as they are called in it's code). 

An example game object could look like this, for CAH_BOTZIE's purposes.

Note: If timestamps cannot be supplied in UTC, then timezone information should be included in the stamp.

```
{
  start-time: "<utc timestamp>"
  end-time: "<utc timestamp>"
  players: [
    "turt2live"
    "jkcclemens"
  ]
  rounds: 45
  final-scores: {
    turt2live: 22
    jkcclemens: 26
  }
  end-cause: "not_enough_players"
}
```

Note that the rounds is a number. This is because I'll have no problem slamming the API 45 times for round information. If desired, I suppose an array of the previously mentioned round object would suffice.

**Comment by jkcclemens** [comment]
This is how I see a round in JSON. Note that the comments will obviously not be present when produced by the bot. Just an explanation of things on my part.
```json
{
  "number": 2,
  "players": [
    "turt2live",
    "jkcclemens"
  ],
  "blackCard": "You can always <BLANK> when you're <BLANK>.",
  "czar": null,
  "votes": {
    "turt2live": 1,
    "jkcclemens": 3
  },
  "_votes_comment": "This will be null or not present if not a vote",
  "plays": {
    "turt2live": [
      "First card",
      "Second card"
    ],
    "jkcclemens": [ ... ]
  },
  "winner": "jkcclemens",
  "scoreDelta": {
    "turt2live": 0,
    "jkcclemens": 1
  },
  "_scoreDelta_comment": "Difference that this round made in the score",
  "result": "SUCCESSFUL",
  "_result_comment": "Text of an enum. Possible values \"CZAR_LEFT\" etc."
}
```

**Comment by turt2live** [comment]
Another proposed round format: http://i.turt2live.com/zu3y.txt

**Comment by jkcclemens** [comment]
Mostly as a note for myself, for the ```handIndex```, I'll have to store the index (and indices) in the Play object.

**Comment by kashike** [comment]
I'd like to see the network name included in results.

**Comment by jkcclemens** [comment]
@kashike For the game object or the round object? Also, why? The bot doesn't do multiple networks at once.

**Comment by jkcclemens** [comment]
Game should hold on to RoundSnapshots whenever a CurrentRound ends. GameSnapshot should have this same list available. GameSnapshot should be serialized (either JSON or Java object) into a List (JSON or Java object again?) of previous games for the given channel.

There should be some sort of History class which has a cache of previously retrieved GameSnapshots (from the serialized list file). The cache should expire after a set time period after the last access (thank you, Guava).

Of course, getting the game via the history API should **not** return ALL of the RoundSnapshots in JSON form, but a summary, or even just a number (most likely), so some manipulation will have to be done if using the #toJSON() method. Otherwise, a JSONWriter can be used to custom generate, or even the ObjectMapper can have mixins applied to just ignore the method to retrieve the RoundSnapshots.
